// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Hero() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"hero-overlay\" class=\"absolute top-8 left-1/2 -translate-x-1/2 z-[1000] w-[90%] sm:w-[600px] hero-overlay rounded-xl shadow-xl p-6 flex flex-col items-center text-center gap-4\"><button onclick=\"closeHero()\" aria-label=\"Close overlay\" class=\"absolute top-2 right-2 text-gray-600 hover:text-gray-800 text-2xl leading-none\">&times;</button><h2 class=\"text-3xl font-extrabold text-gray-900 drop-shadow-sm\">Discover Scotland <span class=\"block text-4xl md:text-5xl bg-clip-text text-transparent bg-gradient-to-r from-blue-600 via-teal-500 to-green-500 tracking-tight\">Munros Map</span></h2><p class=\"text-gray-700 max-w-prose text-sm sm:text-base\">Explore every Scottish Munro peak on an interactive map. Click a summit to see height, routes, photos and more.</p><div class=\"flex gap-3\"><button onclick=\"closeHero()\" class=\"px-5 py-2 rounded-lg text-white font-semibold bg-blue-600 hover:bg-blue-700 shadow\">Start Exploring</button> <a href=\"https://en.wikipedia.org/wiki/Munro\" target=\"_blank\" rel=\"noreferrer\" class=\"px-5 py-2 rounded-lg font-semibold bg-white/70 border border-blue-600 text-blue-700 hover:bg-white\">What is a Munro?</a></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
